/**
 * build-tokens.mjs
 * -----------------------------------------------------------------------------
 * Reads the single source of truth (design-system/tokens.json, W3C DTCG format)
 * and generates two consumable artifacts:
 *
 *   design-system/generated/tokens.css  — CSS custom properties for :root and
 *                                         [data-theme="dark"]. Imported by
 *                                         app/globals.css.
 *   design-system/generated/tokens.ts   — a typed object consumed by
 *                                         tailwind.config.ts and app code
 *                                         (e.g. lib/motion.ts).
 *
 * Run it with `npm run tokens`. It also runs automatically via `predev` /
 * `prebuild`, so the generated files are always in sync with tokens.json.
 *
 * Workflow: edit tokens.json -> run `npm run tokens` -> commit both the JSON
 * and the regenerated files.
 * -----------------------------------------------------------------------------
 */
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const root = resolve(here, "..");
const SRC = resolve(root, "design-system/tokens.json");
const OUT_DIR = resolve(root, "design-system/generated");

const t = JSON.parse(readFileSync(SRC, "utf8"));

/** "primaryDark" -> "primary-dark" */
const kebab = (s) =>
  String(s)
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .replace(/_/g, "-")
    .toLowerCase();

const val = (token) => token.$value;
const bezier = (arr) => `cubic-bezier(${arr.join(", ")})`;

/** Object.entries / Object.keys that skip DTCG metadata keys ($type, $value…). */
const entries = (o) => Object.entries(o).filter(([k]) => !k.startsWith("$"));
const keys = (o) => Object.keys(o).filter((k) => !k.startsWith("$"));

/** next/font exposes each family as `--font-<family>` (e.g. --font-sora). */
const fontStack = (family) => {
  const generic =
    'ui-sans-serif, system-ui, -apple-system, "Segoe UI", Roboto, sans-serif';
  return `var(--font-${kebab(family)}), "${family}", ${generic}`;
};

/* ---------------------------------------------------------------- CSS output */

const rootLines = [];
const darkLines = [];

// Brand colors (mode-independent defaults; dark overrides added below).
for (const [k, tok] of entries(t.color.brand)) {
  rootLines.push([`--color-brand-${kebab(k)}`, val(tok)]);
}
// Light theme semantic colors -> :root
for (const group of ["surface", "text", "border"]) {
  for (const [k, tok] of entries(t.color.light[group])) {
    rootLines.push([`--color-${group}-${kebab(k)}`, val(tok)]);
  }
}
// Dark theme overrides -> [data-theme="dark"]
for (const [k, tok] of entries(t.color.dark.brand)) {
  darkLines.push([`--color-brand-${kebab(k)}`, val(tok)]);
}
for (const group of ["surface", "text", "border"]) {
  for (const [k, tok] of entries(t.color.dark[group])) {
    darkLines.push([`--color-${group}-${kebab(k)}`, val(tok)]);
  }
}

// Typography
rootLines.push(["--font-family-heading", fontStack(val(t.font.family.heading))]);
rootLines.push(["--font-family-body", fontStack(val(t.font.family.body))]);
for (const [k, tok] of entries(t.font.weight))
  rootLines.push([`--font-weight-${kebab(k)}`, String(val(tok))]);
for (const [k, tok] of entries(t.font.size))
  rootLines.push([`--font-size-${kebab(k)}`, val(tok)]);
for (const [k, tok] of entries(t.font.lineHeight))
  rootLines.push([`--line-height-${kebab(k)}`, val(tok)]);
for (const [k, tok] of entries(t.font.letterSpacing))
  rootLines.push([`--letter-spacing-${kebab(k)}`, val(tok)]);

// Spacing / radius / shadow
for (const [k, tok] of entries(t.space))
  rootLines.push([`--space-${kebab(k)}`, val(tok)]);
for (const [k, tok] of entries(t.radius))
  rootLines.push([`--radius-${kebab(k)}`, val(tok)]);
for (const [k, tok] of entries(t.shadow))
  rootLines.push([`--shadow-${kebab(k)}`, val(tok)]);

// Motion
for (const [k, tok] of entries(t.motion.duration))
  rootLines.push([`--motion-duration-${kebab(k)}`, val(tok)]);
for (const [k, tok] of entries(t.motion.loop))
  rootLines.push([`--motion-loop-${kebab(k)}`, val(tok)]);
for (const [k, tok] of entries(t.motion.ease))
  rootLines.push([`--motion-ease-${kebab(k)}`, bezier(val(tok))]);

// Icons
for (const [k, tok] of entries(t.icon.size))
  rootLines.push([`--icon-size-${kebab(k)}`, val(tok)]);

const block = (lines) =>
  lines.map(([name, v]) => `  ${name}: ${v};`).join("\n");

const css = `/* AUTO-GENERATED by scripts/build-tokens.mjs — do not edit by hand.
   Edit design-system/tokens.json, then run \`npm run tokens\`. */

:root {
${block(rootLines)}
}

[data-theme="dark"] {
${block(darkLines)}
}
`;

/* ----------------------------------------------------------------- TS output */

const cssVar = (name) => `var(${name})`;

const colorObj = {
  brand: {
    DEFAULT: cssVar("--color-brand-primary"),
    primary: cssVar("--color-brand-primary"),
    "primary-dark": cssVar("--color-brand-primary-dark"),
    accent: cssVar("--color-brand-accent"),
    tint: cssVar("--color-brand-tint"),
    "on-brand": cssVar("--color-brand-on-brand"),
    glow: cssVar("--color-brand-glow"),
  },
  surface: {
    bg: cssVar("--color-surface-bg"),
    card: cssVar("--color-surface-card"),
    muted: cssVar("--color-surface-muted"),
    scrim: cssVar("--color-surface-scrim"),
  },
  text: {
    primary: cssVar("--color-text-primary"),
    secondary: cssVar("--color-text-secondary"),
  },
  border: {
    DEFAULT: cssVar("--color-border-default"),
    default: cssVar("--color-border-default"),
  },
};

// Tailwind fontSize tuple format: [size, { lineHeight, letterSpacing? }]
const fontSizeObj = {};
for (const k of keys(t.font.size)) {
  fontSizeObj[k] = [
    cssVar(`--font-size-${kebab(k)}`),
    { lineHeight: cssVar(`--line-height-${kebab(k)}`) },
  ];
}

const mapVars = (obj, prefix) =>
  Object.fromEntries(
    keys(obj).map((k) => [k, cssVar(`${prefix}-${kebab(k)}`)]),
  );

const tsObj = {
  color: colorObj,
  fontFamily: {
    heading: cssVar("--font-family-heading"),
    body: cssVar("--font-family-body"),
  },
  fontWeight: mapVars(t.font.weight, "--font-weight"),
  fontSize: fontSizeObj,
  letterSpacing: mapVars(t.font.letterSpacing, "--letter-spacing"),
  space: mapVars(t.space, "--space"),
  radius: mapVars(t.radius, "--radius"),
  shadow: mapVars(t.shadow, "--shadow"),
  motion: {
    duration: mapVars(t.motion.duration, "--motion-duration"),
    loop: mapVars(t.motion.loop, "--motion-loop"),
    ease: mapVars(t.motion.ease, "--motion-ease"),
  },
  iconSize: mapVars(t.icon.size, "--icon-size"),
  // Raw px numbers + stroke width for the <Icon /> component (lucide needs numbers).
  iconSizePx: Object.fromEntries(
    entries(t.icon.size).map(([k, tok]) => [k, parseFloat(val(tok))]),
  ),
  iconStrokeWidth: val(t.icon.strokeWidth),
  // Raw numeric values for Framer Motion (seconds + bezier arrays).
  motionRaw: {
    duration: Object.fromEntries(
      entries(t.motion.duration).map(([k, tok]) => [
        k,
        parseFloat(val(tok)) / 1000,
      ]),
    ),
    ease: Object.fromEntries(
      entries(t.motion.ease).map(([k, tok]) => [k, val(tok)]),
    ),
  },
};

const ts = `// AUTO-GENERATED by scripts/build-tokens.mjs — do not edit by hand.
// Edit design-system/tokens.json, then run \`npm run tokens\`.

export const tokens = ${JSON.stringify(tsObj, null, 2)} as const;

export type Tokens = typeof tokens;
`;

/* ------------------------------------------------------------------ write it */

mkdirSync(OUT_DIR, { recursive: true });
writeFileSync(resolve(OUT_DIR, "tokens.css"), css);
writeFileSync(resolve(OUT_DIR, "tokens.ts"), ts);

console.log(
  `✓ tokens: ${rootLines.length} :root vars, ${darkLines.length} dark overrides -> design-system/generated/`,
);
